modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="machinometry"
version="${file.jarVersion}"
displayName="Machinometry"
description='''Dedicated factory meters and gauges for item, fluid, and energy systems.'''
[[dependencies.machinometry]]
modId="forge"
mandatory=true
versionRange="[47.3.12,)"
ordering="NONE"
side="BOTH"
[[dependencies.machinometry]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
