modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"
[[mods]]
modId="machinometry"
version="${file.jarVersion}"
displayName="Machinometry"
description='''Dedicated factory meters and gauges for item, fluid, and energy systems.'''
[[dependencies.machinometry]]
modId="neoforge"
type="required"
versionRange="[21.1.240,)"
ordering="NONE"
side="BOTH"
[[dependencies.machinometry]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
